<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Talker Town'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
         ->prependStylesheet($this->basePath() . '/css/style.css')
         ->prependStylesheet($this->basePath() . '/libs/JScript-Render/css/JScriptRender.css')
         ->prependStylesheet($this->basePath() . '/libs/CSS-Render/css-render.css')
         ->prependStylesheet($this->basePath() . '/libs/Semantic-UI-1.5.0/dist/semantic.min.css')
         ->prependStylesheet($this->basePath() . '/libs/jquery-ui-1.10.4/themes/flick/jquery-ui.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
         ->prependFile($this->basePath() . '/js/script.js')
         ->prependFile($this->basePath() . '/js/Comet.js')
         ->prependFile($this->basePath() . '/libs/JScript-Render/JScriptRender.js')
         ->prependFile($this->basePath() . '/libs/Semantic-UI-1.5.0/dist/semantic.min.js')         
         ->prependFile($this->basePath() . '/libs/jquery-ui-1.10.4/ui/jquery-ui.js')
         ->prependFile($this->basePath() . '/libs/jquery/plugins/carhartl-jquery-cookie-92b7715/jquery.cookie.js')
         ->prependFile($this->basePath() . '/libs/jquery/jquery-2.1.1/jquery-2.1.1.min.js')
         ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
         ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body class="purple-background">
        <div class="purple-background">

            <div class="ui secondary menu">
                <a href="<?php echo $this->url('home') ?>" class="item active">
                    <i class="home icon"></i> <?php echo $this->translate('Talker Town') ?>
                </a>

                <div class="right menu">
                    <!--<a href="<?= $this->url('application') . '/index/index'; ?>" class="row item">
                        <i class="users icon"></i> <?php echo $this->translate('Register') ?>
                    </a>-->    
                    <!--<a href="#" class="row item">
                        <i class="settings icon"></i>
                    </a>-->  
                    <iframe id='fb-like' src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fpages%2FTalker-Town%2F401780699989247&amp;width&amp;layout=button_count&amp;action=like&amp;show_faces=true&amp;share=true&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:21px; max-width: 180px" allowTransparency="true"></iframe>
                    <iframe class="github" src="http://ghbtns.com/github-btn.html?user=PleetsApps&amp;repo=Talker-Town&amp;type=watch&amp;count=true" allowtransparency="true" frameborder="0" scrolling="0" width="100" height="20"></iframe>
                    <style>
                    @media (max-width: 450px) {
                        #fb-like
                        {
                            display: none;
                        }
                    }
                    </style>
                </div>
            </div>

            <div style="padding: 0 5px">
                <?php echo $this->content; ?>
                <div id="footer-mobile" class="purple-contrast">
                    <br />
                    <footer>
                        <p>&copy; 2014 by Pleets Apps. <?php echo $this->translate('All rights reserved.') ?></p>
                    </footer>
                </div>
            </div> <!-- /container -->
            <?php echo $this->inlineScript() ?>

            <div id="private-messages"></div>

        </div>
    </body>
</html>
