<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Talker Town'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
         ->prependStylesheet($this->basePath() . '/css/style.css')
         ->prependStylesheet($this->basePath() . '/libs/JScript-Render/css/JScriptRender.css')
         ->prependStylesheet($this->basePath() . '/libs/CSS-Render/css-render.css')
         ->prependStylesheet($this->basePath() . '/libs/Semantic-UI-1.5.0/dist/semantic.min.css')
         ->prependStylesheet($this->basePath() . '/libs/jquery-ui-1.10.4/themes/flick/jquery-ui.css')
         ->prependStylesheet($this->basePath() . '/libs/bootstrap-3.1.1/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
         ->prependFile($this->basePath() . '/js/settings.js')
         ->prependFile($this->basePath() . '/js/Script.js')
         ->prependFile($this->basePath() . '/js/Comet.js')
         ->prependFile($this->basePath() . '/libs/JScript-Render/JScriptRender.js')
         ->prependFile($this->basePath() . '/libs/Semantic-UI-1.5.0/dist/semantic.min.js')         
         ->prependFile($this->basePath() . '/libs/bootstrap-3.1.1/js/bootstrap.min.js')
         ->prependFile($this->basePath() . '/libs/jquery-ui-1.10.4/ui/jquery-ui.js')
         ->prependFile($this->basePath() . '/libs/jquery/plugins/carhartl-jquery-cookie-92b7715/jquery.cookie.js')
         ->prependFile($this->basePath() . '/libs/jquery/jquery-2.1.1/jquery-2.1.1.min.js')
         ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
         ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="[ZF]"/>&nbsp;<?php echo $this->translate('Talker Town') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <div id="footer-mobile">
                <hr />
                <footer>
                    <p>&copy; 2014 by Pleets Apps. <?php echo $this->translate('All rights reserved.') ?></p>
                </footer>
            </div>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
