<?php if (isset($Exception)): ?>
<div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong><span class="glyphicon glyphicon-exclamation-sign"></span></strong> <?= $Exception ?>
</div>
<?php endif; ?>

<?php $title = $this->translate('User Login'); $this->headTitle($title); ?>

<?php 
    $formLabel = $this->plugin('formLabel');
    $username = $form->get('username');

    $form = $this->form->prepare();

    $form->setAttributes(array(
        'action' => $this->url('application') . '/index/login',
        'class' => 'ui large form',
        'method' => 'post',
    ));
?>

<div class="ui segment">

    <h1 class="ui basic header center aligned"><?= $this->escapeHtml($title) ?></h1>

    <?php if (isset($form)): ?>
        
        <?= $this->form()->openTag($form) ?>
            
            <div class="fields">
                <div class="required ten wide field">
                    <?= $formLabel->openTag() . $username->getOption('label') . $formLabel->closeTag() ?>
                    <div class="ui large left icon input">
                        <?= $this->formInput($username) ?>
                        <?= $this->formElementErrors($username) ?>
                        <i class="user icon"></i>
                    </div>
                </div>

                <div class="six wide field">
                    <label><?= $this->translate("Gender") ?></label>
                    <div class="ui selection dropdown">
                        <input name="genders_id" type="hidden">
                        <div class="default text"><?= $this->translate("Gender") ?></div>
                        <i class="dropdown icon"></i>
                        <div class="menu">
                            <?php
                                foreach ($genders as $gender) {
                                    ?><div class="item" data-value="<?= $gender["genders_id"] ?>"><?= $this->translate($gender["name"]) ?></div><?php
                                }
                            ?>
                        </div>
                    </div>                    
                </div>
            </div>

            <input type="hidden" name="avatar" id="avatar" value="11">
            <div class="tk-gallery selectable cyclic" data-input="avatar">
                <div class="items">
                    <?php for($k = 1; $k<=11; $k++): ?>
                        <?php for($i = 1; $i<=8; $i++): ?>
                            <div class="item" data-value="<?= $k.$i ?>" style="background-position: calc(-<?= ($i - 1) ?>*77.4px) calc(-<?= ($k - 1) ?>*74px);"></div>
                        <?php endfor; ?>
                    <?php endfor; ?>                    
                </div>

                <div class="controls">
                    <button class="ui left labeled icon button control-left" type="button">
                        <i class="left arrow icon"></i>
                        <?= $this->translate("Prev") ?>
                    </button>

                    <button class="ui right labeled icon button control-right" type="button">
                        <i class="right arrow icon"></i>
                        <?= $this->translate("Next") ?>
                    </button>                    
                </div>

                <div class="mobile controls">
                    <button class="ui icon button control-left" type="button">
                        <i class="left arrow icon"></i>
                    </button>

                    <button class="ui icon button control-right" type="button">
                        <i class="right arrow icon"></i>
                    </button>
                </div>

            </div><br />

            <?php if (!$xmlHttpRequest): ?>
                <?= $this->formSubmit($form->get('submit')) ?>
            <?php endif; ?>

        <?= $this->form()->closeTag() ?>

        <div class="ui basic center aligned segment">
            <p><?= $this->translate("The best city on the Internet") ?></p>
        </div>        
    <?php endif; ?>

</div>

<div class="ui segment">
    <?php if (!$xmlHttpRequest): ?>
        <?= $this->translate("You can register to obtain some advantages here! ") ?> 
        <a href="<?= $this->url('application') . '/index/index'; ?>" class="ui inverted green button">
            <?= $this->translate('Register') ?>
        </a>
    <?php endif; ?>    
</div>