<div class="ui right aligned grid">
	<div class="left floated left aligned eight wide column">
		<button type="button" class="ui labeled orange icon button" id="show-users">
			<i class="content icon"></i>
			Users
		</button>			
	</div>
	<div class="right floated right aligned eight wide column">
		<a href="<?= $this->url('application') . '/index/logout' ?>" class="ui labeled orange icon button">
		 	<i class="power icon"></i>
		 	Logout
		</a>			
	</div>
</div>

<div class="ui segment thin sidebar">
 	<div class="ui selection list" id="online_users">
		<div class="item">
			<img class="ui avatar image" style="background-position: 0px 1px">
			<div class="content"><div class="header"><?= $username ?></div></div>
		</div> 		
 	</div>	
</div>

<div class="ui piled segment" id="outer-content">
	<div id="content"></div>
</div>
<form action="" method="get" id="chat" class="ui form">
	<input type="hidden" id='current-session' value='<?= $username ?>' />
	<?php
		$colors = array("#2A9426", "#952EBD", "#235EB7", "#C97721", "#21C9B5", "#D0734B", "#D04BA6", "#A6B712", "#1F34BC", "#CB1851");
		$keys = array_rand($colors, 2);
		$color = $colors[$keys[0]];
	?>
	<input type="hidden" id='user-color' value='<?= $color ?>' />
	<div class="ui grid">
		<div class="twelve wide mobile only six wide tablet only six wide computer only six wide  large monitor only six wide widescreen only column" style='padding-right: 1px'>
			<div class="ui small icon input">
		   		<input type="text" name="word" id="word" autofocus="autofocus" placeholder="message" />
			</div>
		</div>
		<div class="four wide column" style='padding-left: 1px'>			
			<button type='sumbit' class="ui small icon submit orange button"><i class="chevron right icon"></i></button>
			<!--<input type="submit" name="submit" value="Send" class="ui small submit button" />-->
		</div>
	</div>
</form><br />

<div class="purple-contrast emoticonsPanel" style='margin-top: 5px'>
	<div class="panelCell"><a data-text=':)' class="emoticon emoticon_smile"></a></div>
	<div class="panelCell"><a data-text=':(' class="emoticon emoticon_frown"></a></div>
	<div class="panelCell"><a data-text=':P' class="emoticon emoticon_tongue"></a></div>
	<div class="panelCell"><a data-text='=D' class="emoticon emoticon_grin" ></a></div>
	<div class="panelCell"><a data-text=':o' class="emoticon emoticon_gasp"></a></div>
	<div class="panelCell"><a data-text=';)' class="emoticon emoticon_wink"></a></div>
	<div class="panelCell"><a data-text=':v' class="emoticon emoticon_pacman"></a></div>
	<!--<div class="panelCell"><a data-text='>:(' class="emoticon emoticon_grumpy"></a></div>-->
	<div class="panelCell"><a data-text=':/' class="emoticon emoticon_unsure"></a></div>
	<div class="panelCell"><a data-text=":'(" class="emoticon emoticon_cry"></a></div>
	<div class="panelCell"><a data-text='^_^' class="emoticon emoticon_kiki"></a></div>
	<div class="panelCell"><a data-text='8-)' class="emoticon emoticon_glasses"></a></div>
	<!--<div class="panelCell"><a data-text='<3' class="emoticon emoticon_heart"></a></div>-->
	<div class="panelCell"><a data-text='3:)' class="emoticon emoticon_devil"></a></div>
	<div class="panelCell"><a data-text='O:)' class="emoticon emoticon_angel"></a></div>
	<div class="panelCell"><a data-text='-_-' class="emoticon emoticon_squint"></a></div>
	<div class="panelCell"><a data-text='o.O' class="emoticon emoticon_confused"></a></div>
	<!--<div class="panelCell"><a data-text='>:o' class="emoticon emoticon_upset"></a></div>-->
	<div class="panelCell"><a data-text=':3' class="emoticon emoticon_colonthree"></a></div>
	<div class="panelCell"><a data-text='(y)' class="emoticon emoticon_like"></a></div>
</div>

<div class="purple-contrast">
	<span id="state">offline</span>

	<input type="file" id="file-reader-onchange" value="" multiple="multiple" />
	<div id="file-reader-ondrop" class="drop" style="overflow: hidden; min-height: 50px">
		<span style="color: #C0C0C0; font-size: 25px;">Drop files here</span>
	</div>

	<div id="file_reader_ondrop_response"></div>
	<div id="file_reader_response"></div>
</div>


<!-- Notification audio -->
<audio id='notification-audio' src='<?= $this->basePath("audio/notification.wav") ?>' style='display: none'>
<source src='<?= $this->basePath("audio/notification.wav") ?>' type='audio/wav'>
</audio>

<div class="semantic ui modal" id="lost-session-message">
	<i class="close icon"></i>
	<div class="header">
		Lost session
	</div>
	<div class="content">
		<div class="description">
			You must login again!. You will be redirected in 5 seconds ...
		</div>
	</div>
	<div class="actions">
		<div class="ui button">Cancel</div>
		<div class="ui button">OK</div>
	</div>
</div>
