<div class="ui right aligned grid">
	<div class="left floated left aligned eight wide column">
		<button type="button" class="ui labeled icon button" id="show-users">
			<i class="content icon"></i>
			Users
		</button>			
	</div>
	<div class="right floated right aligned eight wide column">
		<a href="<?= $this->url('application') . '/index/logout' ?>" class="ui labeled icon button">
		 	<i class="power icon"></i>
		 	Logout
		</a>			
	</div>
</div>

<div class="ui segment thin sidebar">
 	<div class="ui animated selection list" id="online_users">
		<div class="item">
			<img class="ui avatar image" style="background-position: 0px 1px">
			<div class="content"><div class="header"><?= $username ?></div></div>
		</div> 		
 	</div>	
</div>

<div class="ui piled segment" id="outer-content">
	<div id="content"></div>
</div>
<form action="" method="get" id="chat" class="ui form">
	<input type="hidden" id='current-session' value='<?= $username ?>' />
	<div class="ui grid">
		<div class="twelve wide mobile only six wide tablet only six wide computer only six wide  large monitor only six wide widescreen only column" style='padding-right: 1px'>
			<div class="ui small icon input">
		   		<input type="text" name="word" id="word" autofocus="autofocus" placeholder="message" />
			</div>
		</div>
		<div class="four wide column" style='padding-left: 1px'>
			<button type='sumbit' class="ui small icon submit button"><i class="chevron right icon"></i></button>
			<!--<input type="submit" name="submit" value="Send" class="ui small submit button" />-->
		</div>		
	</div>
</form>

<span id="state">offline</span>

<input type="file" id="file-reader-onchange" value="" multiple="multiple" />
<div id="file-reader-ondrop" class="drop" style="overflow: hidden; min-height: 50px">
	<span style="color: #C0C0C0; font-size: 25px;">Drop files here</span>
</div>

<div id="file_reader_ondrop_response"></div>
<div id="file_reader_response"></div>

<!-- Notification audio -->
<audio id='notification-audio' src='<?= $this->basePath("audio/notification.wav") ?>' style='display: none'>
<source src='<?= $this->basePath("audio/notification.wav") ?>' type='audio/wav'>
</audio>

<div class="semantic ui modal" id="lost-session-message">
	<i class="close icon"></i>
	<div class="header">
		Lost session
	</div>
	<div class="content">
		<div class="description">
			You must login again!. You will be redirected in 5 seconds ...
		</div>
	</div>
	<div class="actions">
		<div class="ui button">Cancel</div>
		<div class="ui button">OK</div>
	</div>
</div>
